"""Create donor profile model

Revision ID: 257d6b09523a
Revises: a6442aca948e
Create Date: 2026-06-20 19:50:56.068649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257d6b09523a'
down_revision = 'a6442aca948e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('last_donation_date', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('medical_eligible', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donor_profile')
    # ### end Alembic commands ###
