"""Add prescription document to blood requests

Revision ID: 269696c72b84
Revises: f6c5d69d561a
Create Date: 2026-06-21 16:47:02.113407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269696c72b84'
down_revision = 'f6c5d69d561a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription_filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prescription_original_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.drop_column('prescription_original_name')
        batch_op.drop_column('prescription_filename')

    # ### end Alembic commands ###
