"""Add emergency blood request alerts

Revision ID: 2a0e620351a0
Revises: 7df26a6940ad
Create Date: 2026-06-24 20:14:51.350549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0e620351a0'
down_revision = '7df26a6940ad'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'blood_request',
        sa.Column(
            'is_emergency',
            sa.Boolean(),
            server_default=sa.text('0'),
            nullable=False,
        ),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.drop_column('is_emergency')

    # ### end Alembic commands ###
