"""Add donation completion flow

Revision ID: 579b59146ebc
Revises: 9ec33585d514
Create Date: 2026-06-22 22:12:31.538319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579b59146ebc'
down_revision = '9ec33585d514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_request_id', sa.Integer(), nullable=False),
    sa.Column('donor_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('donor_completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blood_request_id'], ['blood_request.id'], ),
    sa.ForeignKeyConstraint(['donor_profile_id'], ['donor_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blood_request_id', 'donor_profile_id', name='uq_donation_request_donor')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_blood_request_id'), ['blood_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_donor_profile_id'), ['donor_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_status'))
        batch_op.drop_index(batch_op.f('ix_donation_donor_profile_id'))
        batch_op.drop_index(batch_op.f('ix_donation_blood_request_id'))

    op.drop_table('donation')
    # ### end Alembic commands ###
