"""Add blood group proof to donor profiles

Revision ID: 77bca1944511
Revises: 269696c72b84
Create Date: 2026-06-21 17:04:02.605665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bca1944511'
down_revision = '269696c72b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_group_proof_filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('blood_group_proof_original_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.drop_column('blood_group_proof_original_name')
        batch_op.drop_column('blood_group_proof_filename')

    # ### end Alembic commands ###
