"""Add donor reward badges

Revision ID: 7df26a6940ad
Revises: 579b59146ebc
Create Date: 2026-06-24 19:47:42.382262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df26a6940ad'
down_revision = '579b59146ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_count', sa.Integer(), server_default='0', nullable=False))

    op.execute(
        """
        UPDATE donor_profile
        SET donation_count = (
            SELECT COUNT(*)
            FROM donation
            WHERE donation.donor_profile_id = donor_profile.id
            AND donation.status = 'Completed'
        )
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.drop_column('donation_count')

    # ### end Alembic commands ###
