"""Create blood request model

Revision ID: d5c368c32646
Revises: 257d6b09523a
Create Date: 2026-06-20 20:15:01.440412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c368c32646'
down_revision = '257d6b09523a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('units_required', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('hospital_address', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blood_request_requester_id'), ['requester_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blood_request_requester_id'))

    op.drop_table('blood_request')
    # ### end Alembic commands ###
