"""Add donation private chat

Revision ID: f3660ad5667c
Revises: 6410398d5cd6
Create Date: 2026-07-08 19:30:27.497233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3660ad5667c'
down_revision = '6410398d5cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donation.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_donation_id'), ['donation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_donation_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_created_at'))

    op.drop_table('chat_message')
    # ### end Alembic commands ###
