"""Add verification review fields

Revision ID: f6c5d69d561a
Revises: d5c368c32646
Create Date: 2026-06-20 21:20:28.144924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c5d69d561a'
down_revision = 'd5c368c32646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key('fk_blood_request_reviewed_by_id_user', 'user', ['reviewed_by_id'], ['id'])

    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key('fk_donor_profile_reviewed_by_id_user', 'user', ['reviewed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_profile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donor_profile_reviewed_by_id_user', type_='foreignkey')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')

    with op.batch_alter_table('blood_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blood_request_reviewed_by_id_user', type_='foreignkey')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')

    # ### end Alembic commands ###
